config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :messages
  get 'groups/show'

  root to: "home#index"
  devise_for :user2, controllers: { sessions: 'sessions' }

  get 'collections/new' => 'collections#new', as: :new_collections
  post 'collections/create' => 'collections#create'
  get 'collections/:id' => 'collections#show', as: :see_one_collections
  get 'collections/:id/editar' => 'collections#edit', as: :edit_collections
  post 'collections/:id/update' => 'collections#update', as: :update_collections
  delete 'collections/:id/borrar' => 'collections#delete', as: :delete_collections

  get 'events/new' => 'events#new', as: :newevents
  post 'events/create' => 'events#create'
  get 'events/:id' => 'events#show', as: :see_one_events
  get 'events/:id/editar' => 'events#edit', as: :edit_events
  post 'events/:id/update' => 'events#update', as: :update_events
  delete 'events/:id/borrar' => 'events#delete', as: :delete_events

  get 'groups' => 'groups#index', as: :all_groups
  get 'groups/new' => 'groups#new', as: :new_groups
  post 'groups/create' => 'groups#create'
  get 'groups/:id' => 'groups#show', as: :see_one_ugroups
  get 'groups/:id/editar' => 'groups#edit', as: :edit_groups
  post 'groups/:id/update' => 'groups#update', as: :update_groups
  delete 'groups/:id/borrar' => 'groups#delete', as: :delete_groups

  get 'group_list/:id' => 'group_list#show'
  post 'group_list/' =>'group_list#create'
  put 'group_list/:id' => 'group_list#update'
  get 'notes' => 'notes#index', as: :all_notes
  get 'notes/new' => 'notes#new', as: :new_notes
  post 'notes/create' => 'notes#create', as: :create_notes
  get 'notes/:id' => 'notes#show', as: :see_one_notes
  put 'notes/:id/update' => 'notes#update', as: :update_notes
  delete 'notes/:id/borrar' => 'notes#delete', as: :delete_notes

  get 'private_Conversations' => 'private_conversation#index', as: :see_privateConversation
  get 'private_Conversations/new' => 'private_conversation#new', as: :new_privateConversation
  post 'private_Conversations/create' => 'private_conversation#create'
  get 'private_Conversations/:id' => 'private_conversation#show', as: :see_one_privateConversation
  get 'private_Conversations/:id/editar' => 'private_conversation#edit', as: :edit_privateConversation
  post 'private_Conversations/:id/update' => 'private_conversation#update', as: :update_privateConversation
  delete 'private_Conversations/:id/borrar' => 'private_conversation#delete', as: :delete_privateConversation

  get 'private_Messages' => 'private_messages#index', as: :see_privateMessages
  get 'private_Message/new' => 'private_message#new', as: :new_privateMessage
  post 'private_Message/create' => 'private_message#create'

  get 'public_Messages' => 'public_messages#index', as: :see_publicMessages
  get 'public_Message/new' => 'public_message#new', as: :new_publicMessage
  post 'public_Message/create' => 'public_message#create'

  get 'users' => 'users2#index', as: :see_users
  get 'users/new' => 'users2#new', as: :new_user
  post 'users/create' => 'users2#create'
  get 'users/:id' => 'users2#show', as: :see_one_users
  get 'users/:id/editar' => 'users2#edit', as: :edit_users

  put 'users/:id/update' => 'users2#update', as: :update_users

  delete 'users/:id/borrar' => 'users2#delete', as: :delete_users

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :user
  has_many :event
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :group
  has_many :public_message
  has_many :messages
end

app/models/chat_member.rb
class ChatMember < ActiveRecord::Base
  belongs_to :group
  belongs_to :chat
  belongs_to :user2
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :group
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :calendar
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :events
	has_many :collections
	has_many :notes
	has_many :user2
	has_one :chat
end

app/models/group_list.rb
class GroupList < ActiveRecord::Base
  belongs_to :user2
  belongs_to :group
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat_member
  belongs_to :chat
  	def user2Id
  	 user2_id
	end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :group
end

app/models/user2.rb
class User2 < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable
  has_many :group_lists
  has_many :chat

  before_save :ensure_authentication_token

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  private

    def generate_authentication_token
      loop do
        token = Devise.friendly_token
        break token unless User2.where(authentication_token: token).first
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index 
	@user= User2.all	
  	 	respond_to do |f|
		  	f.json{}
		    f.html{}
 		end
	end
	def show
    u_id=params[:id] 
    @user= User2.where(id: u_id).first
	end

	def create
		u= User2.new({
			nickname: params[:nickname],
			name: params[:name],
			lastName: params[:lastName],
			birthday: params[:birthday],
			phone: params[phone],
			email: params[:email],
     		password: params[:password],
     		password_confirmation: params[:password]
			})
		u.save 		
	end

	def edit
    u_id=params[:id] 
    @user= User2.where(id: u_id).first
 	end

	 def update
	    u_id=params[:id] 
	    @user= User2.where(id: u_id).first
	    @user.update_attributes(user_params)
	    redirect_to action: :show 
	  end

	 def delete
		#permisos <= devise 
		u_id=params[:id].to_i 
		@user= User2.where(id: u_id).first
		if @user.nil?
		  return redirect_to action: :index
		else
		  @user.destroy 
	    redirect_to action: :index

		end    
	 end

	 def user_params
	 	if @user_params.present?
	 		@user_params
	 	else
	 		@user_params = {	 			
	    	nickname: params[:nickname],
			name: params[:name],
			lastName: params[:lastName],
			birthday: params[:birthday],
			phone: params[:phone],
			email: params[:email]
	 		}
		 	if params[:password].present?
				@params[:password] = params[:password],	
				@params[:password_confirmation] = params[:password]	 		
		 	end
		 	@user_params
	 	end
	 	
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/group_list_helper.rb
module GroupListHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users2_helper.rb
module Users2Helper
end

app/views/user/index.html.erb
<a href="<%= new_user_url%>"> Crear nuevo user </a>
<ul>
<% @user.each do |user| %>
	<li><a href="<%= see_one_users_url(id: user.id) %>"> <%= user.userName %> </a> 
	<% end %>
</ul>

app/views/user/new.html.erb
<h1> Create your user </h1>

 <%= form_tag("/users/create", method: :post) do%>
    
    <p>Username: <%= text_field_tag :username  %></p>
    <p>Password: <%= text_field_tag :password  %></p>
    <p>Name: <%= text_field_tag :name %></p>
    <p>Last Name: <%= text_field_tag :lastName  %></p>
    <p>Birthday: <%= date_field_tag :birthday  %></p>
    <p>E-mail: <%= text_field_tag :email  %></p>

    <p><%= submit_tag 'Crear' %></p>
<% end %>

app/views/user/show.html.erb
<h1> Descripcion de user </h1>
<ul>
	<li> Id: <%= @user.id %></li>
	<li> Username: <%= @user.userName %></li>
	<li> Password: <%= @user.password %></li>
</ul>

<p><a href="<%= edit_users_url%>"> Editar </a></p>
<p><a href="<%= see_users_url%>"> Regresar </a></p>

<!--
<%= form_tag delete_users_url(id: @user.id), method: :delete do%>
	 <p><%= submit_tag 'Borrar' %></p>
<% end %>
-->

 <%= link_to 'Borrar', delete_users_url(id: @user.id), method: :delete %>

app/views/users/edit.html.erb
<h1> Edit a user </h1>

 <%= form_tag(update_users_url({id: @user.id}), method: :post) do%>

    <p>username:<%= text_field_tag :nickname, @user.nickname  %></p>
    <p>password:<%= text_field_tag(:password, @user.password) %></p>
    <p>name:<%= text_field_tag :name, @user.name  %></p>
    <p>last name:<%= text_field_tag :lastName, @user.lastName  %></p>
    <p>birthday:<%= date_field_tag :birthday, @user.birthday  %></p>
    <p>phone:<%= text_field_tag :phone , @user.phone %></p>
    <p>email:<%= text_field_tag :email, @user.email %></p>

    <p><%= submit_tag 'Actualizar' %></p>
    <a href="<%= see_users_url%>"> Cancelar </a>


<% end %>

app/views/users/index.html.erb
<a href="<%= new_user_url%>"> Crear nuevo user </a>
<ul>
<% @user.each do |user| %>
	<li><a href="<%= see_one_users_url(id: user.id) %>"> <%= user.nickname %> </a>
	<% end %>
¡
</ul>

app/views/users/new.html.erb
<h1> Create your user </h1>

 <%= form_tag("/users/create", method: :post) do%>

    <p>Username: <%= text_field_tag :nickname  %></p>
    <p>Password: <%= text_field_tag :password  %></p>
    <p>Name: <%= text_field_tag :name %></p>
    <p>Last Name: <%= text_field_tag :lastName  %></p>
    <p>Birthday: <%= date_field_tag :birthday  %></p>
    <p>Phone: <%= text_field_tag :phone  %></p>
    <p>E-mail: <%= text_field_tag :email  %></p>

    <p><%= submit_tag 'Crear' %></p>

<% end %>

app/views/users/show.html.erb
<h1> Descripcion de user </h1>
<ul>
	<li> Id: <%= @user.id %></li>
	<li> Username: <%= @user.nickname %></li>
	<li> Name: <%= @user.name %></li>
	<li> Last Name: <%= @user.lastName %></li>
	<li> Birthday: <%= @user.birthday %></li>
	<li> Email: <%= @user.email %></li
</ul>

<p><a href="<%= edit_users_url%>"> Editar </a></p>
<p><a href="<%= see_users_url%>"> Regresar </a></p>

<!--
<%= form_tag delete_users_url(id: @user.id), method: :delete do%>
	 <p><%= submit_tag 'Borrar' %></p>
<% end %>
-->

 <%= link_to 'Borrar', delete_users_url(id: @user.id), method: :delete %>